### ISSUE TITLE
[Problem] Installation 

### ISSUE THREAD

**Issue by mykljohn** [FabianWe/django-bootstrap3-multidatepicker#2]
Hi, this looks promising in, but I'm having trouble getting it working. Django 1.8.18, Python 2.7, Bootstrap 3.3.7, django-bootstrap3 9.0

Here's the html generated, but the date button does nothing.

```
<!DOCTYPE html>

<html lang="en-us">

<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>is this loading?
    Multidate Picker Demo
</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"><link href="https://bootswatch.com/lumen/bootstrap.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="//code.jquery.com/jquery.min.js"></script><script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>   

<link href="/static/django_bootstrap3_multidatepicker/bootstrap-datepicker3.standalone.min.css" type="text/css" media="all" rel="stylesheet" />
<script type="text/javascript" src="/static/django_bootstrap3_multidatepicker/django-datepicker.min.js"></script>
<script type="text/javascript" src="/static/django_bootstrap3_multidatepicker/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    id_dates_jsvar.afterChange = function() {
      $('#current_dates li').remove();
      for (var i = 0; i < id_dates_jsvar.dates.length; i++) {
        var date = id_dates_jsvar.dates[i];
        var date_str = '' + date.getUTCFullYear() + '/' + date.getUTCMonth() + '/' + date.getUTCDate();
        $('#current_dates').append($('<li>').text(date_str));
      }
    }
  });
</script>
</head>
<body>
    <div class="container">      
<h1>Multidate Picker Demo</h1>  
        <p>
<form class="form" method="POST">
  <input type='hidden' name='csrfmiddlewaretoken' value='j7KfDYNNHmUrNFUYALSpFTQ8kQxjBXwL' />
  <div class="input-group date-list" id="id_dates_pickers">
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
            </div>
<input class="form-control" id="id_dates" maxlength="1024" name="dates" type="hidden"></input>
<script type="text/javascript">
        var id_dates_jsvar = new DjangoBootstrapDatePicker("#id_dates_pickers", "#id_dates");
        $(document).ready(function() {
            id_dates_jsvar.bind_picker({"multidate": true});
        });
        </script>
  <button class="btn btn-primary" type="submit"><span class="glyphicon glyphicon-circle-arrow-right"></span> Save</button>
</form>
<h2>Currently selected Dates</h2>
<ul id="current_dates">
</ul>
</p>
    </div>
```

**Comment by FabianWe** [comment]
Hi sorry I was on vacation, do you still have a problem with it? Then I could look into it!

**Comment by mykljohn** [comment]
Hi, I got it, the css wasn't loading.  I do have a related question.  How do I initialize the calendar?  I want to set addDisabledDates.

**Comment by mykljohn** [comment]
I got this as well.  :)  I needed to add it to the fields.py widget call:
`    widget = BootstrapDatepickerInput(
            options={
                "format": "yyyy-mm-dd",
                "startDate": "Today",
                "todayHighlight": "True",
                "datesDisabled": ["2017-10-18","2017-10-14","2017-10-21"]
            }
        )
`

**Comment by FabianWe** [comment]
Exactly, options should be used to change the calendar, all options should be listed [here](http://bootstrap-datepicker.readthedocs.io/en/latest/options.html#) by the way (if anyone wants to know).

**Comment by mykljohn** [comment]
@FabianWe Hi, This is nice and easy to use (once I figured everything out :)...
Another question, if you don't mind.

I have 2 related models:

```
class Product(models.Model):
    desc = models.charfield()

class ProductBooking(models.Model):
    product = models.ForeignKey('catalogue.Product')
    booking_date = models.DateField()
```
and I want to display them as a list:   desc, booking_date, but I want the booking date field to display the calendar.  Can you point me in the right direction to do this?

**Comment by mykljohn** [comment]
@FabianWe   One more question...this has the methods to disable dates, but not add dates.  So how can I initialize the calendar with the already selected dates?  I think I found it in the documentation under Multidate:

> The input’s value (if present) is set to a string generated by joining the dates, formatted, with multidateSeparator

So I'm guessing I just have to set the field to a comma delimited string in field.py?

**Comment by mykljohn** [comment]
Ok, I found the setDate method, but I can't get it to work :(  It doesn't work if I treat it as an option.  Any help?
